### ISSUE TITLE
A question about the pooling layer

### ISSUE THREAD

**Issue by tammyyang** [yhenon/pysqueezenet#1]
Hi,

I found this repo and it is really useful, thank you! However, I found the pooling layer was implemented with size=2x2 and stride=1, which is different from the one used in the original paper (kernel size 3x3 with stride=2). I was wondering that if you do this in purpose? I also modify the source code a little bit so it is now using functional API of Keras 1.0 instead of the Graph model. The [source code](https://github.com/DT42/squeezenet_demo) is also public if you are interested.

Many thanks again for publishing the source!

Cheers,
Tammy

**Comment by yhenon** [comment]
Hey, thanks for your interest. I just had a look at the paper again and it's either (a) a bug on my side, or (b) I was relying on a much older version of the paper. I'll go ahead and close this, and mark this repo as being a legacy version.

**Comment by tammyyang** [comment]
Hi yhenon, thanks for your response. For your reference, the reason I think it should be 3x3 and stride 2 is because of Table 1 in v3 of the paper.

**Comment by yhenon** [comment]
I agree with you, fixed in 8f1d6b991a463ee3e57a2464c837643e5d2989f4
